# Previsão do sentimento de consumidores de e-commerce brasileiro a partir de suas avaliações — Regressão Logística

## Contexto

Com a constante evolução tecnológica, o e-commerce é utilizado por muitos brasileiros pela facilidade de compra e pelos preços possivelmente reduzidos. Com isso, surge a curiosidade em compreender como esses consumidores realmente se sentem após a compra: satisfeitos com o produto (de acordo com os comentários positivos) ou insatisfeitos (de acordo com os comentários negativos). Dependendo dos dados obtidos e do nível de satisfação do cliente, é possível identificar a proporção de cada sentimento e quais palavras são mais recorrentes, o que pode indicar de onde vem cada sentimento e orientar melhorias na gestão de produtos.

## Objetivo

O objetivo deste projeto é dar início aos estudos de Aprendizado de Máquina, utilizando dados de um dataset da plataforma Kaggle chamado Merged Olist Brazilian E-Commerce Dataset for EDA (Conjunto de Dados de E-Commerce Brasileiro da Olist Mesclado para EDA), criado para fins educacionais.

Com ele, vou treinar um modelo supervisionado de regressão logística que, com base apenas no comentário do cliente (cada linha representa um pedido), preveja se ele ficou Satisfeito, Neutro ou Insatisfeito após receber a compra. Dessa forma, o modelo poderá generalizar o que aprendeu e classificar novos dados, caso eles cheguem sem rótulo.

Além do treinamento, vou testar o modelo e calcular as seguintes métricas de avaliação:

- Acurácia: mede a proporção de previsões corretas.
- Precisão: avalia a proporção de verdadeiros positivos em relação ao total de positivos previstos.
- Recall: indica a capacidade do modelo de identificar todos os casos positivos.
- F1-score: combina precisão e recall em uma única métrica.

Por fim, vou levantar as palavras mais frequentes nos comentários, para tentar identificar o que levou às avaliações negativas, e realizar algumas análises de estatística descritiva para resumir os resultados obtidos. 

## Entrada e saída do modelo

- **Entrada:** o comentário do cliente (`review_comment_message`), convertido em valores numéricos por meio de Bag of Words.
- **Saída:** o rótulo de satisfação (Satisfeito, Neutro ou Insatisfeito).

## Criação dos rótulos

Além do comentário, cada cliente fornece uma nota de avaliação (`review_score`) de 1 a 5. A partir dela, criei os rótulos de satisfação com a seguinte regra:

| Score | Rótulo |
|---|---|
| 5 e 4 | Satisfeito |
| 3 | Neutro |
| 2 e 1 | Insatisfeito |

O score **não é usado como entrada**, pois isso entregaria a resposta ao modelo. Ele é usado apenas para gerar os rótulos que servem de gabarito durante o treinamento.

## Métodos de validação

Para consolidação dos conhecimentos, dois métodos de validação foram aplicados:

- Validação **holdout**: Os dados foram divididos em treino (80%) e teste (20%). O modelo aprende com os comentários e rótulos do conjunto de treino e, em seguida, prevê os rótulos dos comentários do conjunto de teste, que ele nunca viu. Esses rótulos previstos são comparados com os rótulos reais, obtidos a partir dos scores fornecidos pelos clientes, para verificar se condizem ou não com o resultado esperado.

- Validação **cruzada**: Os dados foram divididos em várias partes, e o modelo foi treinado e testado em diferentes combinações dessas partes.

## Pré-processamento dos dados: Limpeza

In [1]:
# Importa bibliotecas necessárias
import pandas as pd
pd.set_option('display.max_colwidth', None)
import re # operações regex
import nltk # processamento de linguagem natural (PLN)

# biblioteca de machine learning 
from sklearn.feature_extraction.text import CountVectorizer # Vetorização da Linguagem Natural
from sklearn.linear_model import LogisticRegression # Aplicação da Regressão Logística
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_predict # Validações
from sklearn.metrics import classification_report, confusion_matrix # Resultado das validações
from sklearn.pipeline import Pipeline # Para fazer o processo de vetorização e análise após a separação dos dados

nltk.download('stopwords') # lista de stopwords de vários idiomas
nltk.download('punkt_tab') # modelo treinado que sabe onde terminam frases e palavras

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/baee7ae1-eb79-4aaa-9a44-
[nltk_data]     1f43d328681d/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/baee7ae1-eb79-4aaa-9a44-
[nltk_data]     1f43d328681d/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [2]:
# Cria DataFrame
def cria_df(csv, sep):
    
    df = pd.read_csv(csv, sep=sep)
    
    print('Primeira visualização dos dados:')
    display(df.head(30))

    print(40 * '-')

    linhas, colunas = df.shape
    print(f"Os dados possuem {linhas} linhas e {colunas} colunas.")

    print(40 * '-')
    
    tipo_dados = df.dtypes
    print(f"Tipo de dados para cada coluna: \n{tipo_dados}")

    print(40 * '-')
    
    valores_nulos = round((df.isnull().sum() / linhas) * 100, 2)
    print("Proporção de valores nulos por coluna:")
    print(valores_nulos)

    print(40 * '-')
    
    duplicatas = df.duplicated().sum()
    print(f"Quantidade de linhas duplicadas: {duplicatas}")

    print(40 * '-')
    
    return df, valores_nulos

In [3]:
# Realiza limpeza inicial dos dados
def limpa_dados(df, sep):

    # Verifica as características dos dados e guarda os valores das proporções de nulos.
    df, valores_nulos = cria_df(df, sep=sep)

    # Remove duplicatas
    print('Removendo duplicatas...')
    df_sem_duplicatas = df.drop_duplicates(keep='first') # Mantém a primeira linha do registro

    print(40 * '-')

    
    print(f'Verificando se ainda há duplicatas: {df_sem_duplicatas.duplicated().sum()}')

    print(40 * '-')

    # Trata valores nulos
    # Critério que adotei: colunas com a partir de 70% dos valores nulos, removo
    print('Tratando colunas com valores nulos...')
    colunas_nulas = valores_nulos[valores_nulos >= 70].index # extrai o nome das colunas
    df_sem_nulos = df_sem_duplicatas.drop(columns = colunas_nulas)

    print(40 * '-')
    
    print(f'Verificando se ainda há colunas com valores nulos igual ou acima de 70%: \n{df_sem_nulos.isnull().sum()/len(df_sem_nulos)}')

    print(40 * '-')

    # Mostra como os dados estão no momento
    print('Como os dados estão no momento:')
    display(df_sem_nulos.head(30))

    print(40 * '-')

    return df_sem_nulos

In [4]:
# Seleciona variáveis que vão ser usadas no treinamento
dados_limpos = limpa_dados('olist_merged_dataset.csv', ',')

print('Selecionando variáveis pro treinamento...')

print(40 * '-')

dados_limpos = dados_limpos.drop(columns=[
                                          'customer_id',
                                          'order_status', 
                                          'order_purchase_timestamp',
                                          'order_approved_at',
                                          'order_delivered_carrier_date',
                                          'order_delivered_customer_date',
                                          'order_estimated_delivery_date',
                                          'customer_unique_id',
                                          'customer_zip_code_prefix',
                                          'customer_city',
                                          'customer_state',
                                          'order_item_id',
                                          'seller_id',
                                          'shipping_limit_date',
                                          'price',
                                          'freight_value',
                                          'product_name_lenght',
                                          'product_description_lenght',
                                          'product_photos_qty',
                                          'product_weight_g',
                                          'product_length_cm',
                                          'product_height_cm',
                                          'product_width_cm',
                                          'seller_zip_code_prefix',
                                          'seller_city',
                                          'seller_state',
                                          'payment_sequential',
                                          'payment_type',
                                          'payment_installments',
                                          'payment_value',
                                          'review_id',
                                          'review_creation_date',
                                          'review_answer_timestamp',
                                          'delivery_days',
                                          'delivery_delay',
                                          'product_category_name_english'])

# Após excluir colunas que não vão ser utilizadas, confiro se há linhas duplicadas entre essas colunas
print(f'Quantidade de linhas duplicadas após a seleção: {dados_limpos.duplicated().sum()}')

print(40 * '-')

print('Removendo duplicatas...')

print(40 * '-')

dados_limpos['review_comment_message'] = dados_limpos['review_comment_message'].str.strip()
dados_limpos = dados_limpos.drop_duplicates(keep='first', subset=['order_id'])
dados_limpos = dados_limpos.dropna(subset=['review_comment_message'])
dados_limpos = dados_limpos[dados_limpos['review_comment_message'] != ''] # Removendo casos de comentários vazios 


print(f'Shape final: {dados_limpos.shape}')



# Para deixar claro:
# No primeiro momento, analisei se havia linhas duplicadas considerando todas as variáveis. Não havia.
# No segundo momento, analisei se havia linhas duplicadas considerando apenas as colunas selecionadas. Havia.
# No terceiro momento, removi as linhas duplicadas, pois um mesmo pedido pode conter vários produtos
# e, com isso, o comentário de cada pedido se repete em todos os produtos dele.

Primeira visualização dos dados:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,delivery_days,delivery_delay
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.12,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio correto e em boas condições. Apenas a caixa que veio bem amassada e danificada, o que ficará chato, pois se trata de um presente.",2017-10-11,2017-10-12 03:43:48,8.0,-8.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,2.00,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio correto e em boas condições. Apenas a caixa que veio bem amassada e danificada, o que ficará chato, pois se trata de um presente.",2017-10-11,2017-10-12 03:43:48,8.0,-8.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.59,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio correto e em boas condições. Apenas a caixa que veio bem amassada e danificada, o que ficará chato, pois se trata de um presente.",2017-10-11,2017-10-12 03:43:48,8.0,-8.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,1,141.46,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,13.0,-6.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,3,179.12,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18,2018-08-22 19:07:58,9.0,-18.0
5,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,1,72.20,359d03e676b3c069f62cadba8dd3f6e8,5,NaN,O produto foi exatamente o que eu esperava e estava descrito no site e chegou bem antes da data prevista.,2017-12-03,2017-12-05 19:21:58,13.0,-13.0
6,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,1,28.62,e50934924e227544ba8246aeb3770dd4,5,NaN,NaN,2018-02-17,2018-02-18 13:02:51,2.0,-10.0
7,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,80bb27c7c16e8f973207a5086ab329e2,86320,...,6,175.26,89b738e70a1ce346db29a20fb2910161,4,NaN,NaN,2017-07-27,2017-07-27 22:48:30,16.0,-6.0
8,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,932afa1e708222e5821dac9cd5db4cae,26525,...,3,75.16,07d67dd06ed5f88bef11ef6b464e79ae,5,NaN,NaN,2017-05-27,2017-05-28 02:59:57,9.0,-12.0
9,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06,39382392765b6dc74812866ee5ee92a7,99655,...,1,35.95,fc4af8aea8ec3f1a3cd181d3d0cadbd5,1,NaN,NaN,2017-02-03,2017-02-05 01:58:35,9.0,-32.0
10,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,299905e3934e9e181bfb2e164dd4b4f8,18075,...,1,161.42,abc5655186d40772bd6e410420e6a3ed,5,NaN,NaN,2017-08-17,2017-08-18 01:47:32,18.0,-7.0
11,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,299905e3934e9e181bfb2e164dd4b4f8,18075,...,1,8.34,abc5655186d40772bd6e410420e6a3ed,5,NaN,NaN,2017-08-17,2017-08-18 01:47:32,18.0,-7.0
12,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,f2a85dec752b8517b5e58a06ff3cd937,20780,...,1,259.06,15898b543726a832d4137fbef5d1d00e,1,NaN,Aguardando retorno da loja,2017-05-30,2017-05-30 23:13:47,12.0,-9.0
13,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,f2a85dec752b8517b5e58a06ff3cd937,20780,...,1,259.06,15898b543726a832d4137fbef5d1d00e,1,NaN,Aguardando retorno da loja,2017-05-30,2017-05-30 23:13:47,12.0,-9.0
14,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08,782987b81c92239d922aa49d6bd4200b,4278,...,1,114.13,a932e1fddc0c17fc26de56687b48f922,4,NaN,NaN,2017-07-20,2017-07-22 20:11:54,5.0,-20.0
15,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18,e97109680b052ee858d93a539597bba7,35400,...,1,50.13,ed220e853e96b629118a3576e02900b6,5,NaN,NaN,2018-06-20,2018-06-20 15:31:29,12.0,-29.0
16,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08,e2dfa3127fedbbca9707b36304996dab,4812,...,3,32.70,346e42116863ea64d51cef464d8f0c9c,5,NaN,NaN,2018-07-31,2018-08-02 21:15:12,4.0,-9.0
17,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21,04cf8185c71090d28baa4407b2e6d600,5271,...,1,54.36,8f39f09c22b1ceb6e3eb178d8e50bb8a,4,NaN,Gostei do produto,2018-03-13,2018-03-14 10:36:16,11.0,-9.0
18,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04,ccafc1c3f270410521c3c6f3b249870f,74820,...,10,146.45,5a8608437f4b52bec5cd143f37258b5e,5,Nota dez,Obrigado pela atenção. Lojas lannister perfeito em tudo.,2018-07-03,2018-07-03 15:10:07,13.0,-13.0
19,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29,6087cfc70fd833cf2db637a5e6e9d76b,88780,...,4,43.09,0c00083494717bc36977eb15ba4bba01,5,NaN,NaN,2018-01-09,2018-01-12 01:09:35,12.0,-21.0
20,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11,d0ff1a7468fcc46b8fc658ab35d2a12c,13186,...,1,29.75,70c498f6918af37d6444d7846449ea5b,5,NaN,NaN,2017-11-28,2017-11-28 22:12:02,6.0,-14.0
21,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23,634f09f6075fe9032e6c19609ffe995a,44024,...,1,62.15,219cf59cf889bc85babbd1cd1fe30f2d,4,NaN,NaN,2017-11-09,2017-11-10 01:06:29,13.0,-15.0
22,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23,634f09f6075fe9032e6c19609ffe995a,44024,...,1,24.86,219cf59cf889bc85babbd1cd1fe30f2d,4,NaN,NaN,2017-11-09,2017-11-10 01:06:29,13.0,-15.0
23,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23,634f09f6075fe9032e6c19609ffe995a,44024,...,1,5.96,219cf59cf889bc85babbd1cd1fe30f2d,4,NaN,NaN,2017-11-09,2017-11-10 01:06:29,13.0,-15.0
24,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28,d699688533772c15a061e8ce81cb56df,4001,...,1,118.86,38cae21b1b57a95959440380d5b2ef7a,2,NaN,"os correios estäo em greve... näo recebi nenhum aviso de atraso, mas de qqer forma a empresa responsável deveria dar alguma resposta sobre o atraso.",2017-10-01,2017-10-01 17:55:21,21.0,11.0
25,f848643eec1d69395095eb3840d2051e,4fa1cd166fa598be6de80fa84eaade43,delivered,2018-03-15 08:52:40,2018-03-15 09:09:31,2018-03-15 19:52:48,2018-03-19 18:08:32,2018-03-29,68954feaafe4dd638f3bd3e2afa174ec,8473,...,4,88.90,f3d78d82a38fc81f086b0d810edcf3aa,5,NaN,NaN,2018-03-20,2018-03-20 14:35:09,4.0,-10.0
26,2807d0e504d6d4894d41672727bc139f,72ae281627a6102d9b3718528b420f8a,delivered,2018-02-03 20:37:35,2018-02-03 20:50:22,2018-02-05 22:37:28,2018-02-08 16:13:46,2018-02-21,b8df986511d928829c3192c2ed081eba,3323,...,1,17.28,e905f4e4e372b175115c1d6c878b5020,3,NaN,NaN,2018-02-09,2018-02-11 21:45:20,4.0,-13.0
27,95266dbfb7e20354baba07964dac78d5,a166da34890074091a942054b36e4265,delivered,2018-01-08 07:55:29,2018-01-08 08:07:31,2018-01-24 23:16:37,2018-01-26 17:32:38,2018-02-21,451e48381edab7f1f6dbfa6d728616ff,89070,...,3,187.57,1d507207ffd8c75b785304b33e2f6c59,4,NaN,NaN,2018-01-27,2018-01-28 11:42:31,18.0,-26.0
28,f3e7c359154d965827355f39d6b1fdac,62b423aab58096ca514ba6aa06be2f98,delivered,2018-08-09 11:44:40,2018-08-10 03:24:51,2018-08-10 12:29:00,2018-08-13 18:24:27,2018-08-17,9c9242ad7f1b52d926ea76778e1c0c57,18052,...,1,104.11,9a55cbc65c8fad47581da5ebbb2b373e,5,Ótimo,Sempre vou comprar aqui pois é a melhor parabéns,2018-08-14,2018-08-14 21:52:46,4.0,-4.0
29,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12,a25d5f94840d3c6a1a49f271ed83f4ec,21715,...,1,125.43,6a1a8e54de03ab98e6e8ff56e56e507f,2,NaN,Demora muito entregar. Já passou o prazo e ainda não recebi minha encomenda.,2018-03-16,2018-03-20 23:10:58,28.0,9.0

----------------------------------------
Os dados possuem 115609 linhas e 42 colunas.
----------------------------------------
Tipo de dados para cada coluna:
order_id                          object
customer_id                       object
order_status                      object
order_purchase_timestamp          object
order_approved_at                 object
order_delivered_carrier_date      object
order_delivered_customer_date     object
order_estimated_delivery_date     object
customer_unique_id                object
customer_zip_code_prefix           int64
customer_city                     object
customer_state                    object
order_item_id                      int64
product_id                        object
seller_id                         object
shipping_limit_date               object
price                            float64
freight_value                    float64
product_category_name             object
product_name_lenght              float64
product_description_lenght       float64
product_photos_qty               float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
product_category_name_english     object
seller_zip_code_prefix             int64
seller_city                       object
seller_state                      object
payment_sequential                 int64
payment_type                      object
payment_installments               int64
payment_value                    float64
review_id                         object
review_score                       int64
review_comment_title              object
review_comment_message            object
review_creation_date              object
review_answer_timestamp           object
delivery_days                    float64
delivery_delay                   float64
dtype: object
----------------------------------------
Proporção de valores nulos por coluna:
order_id                          0.00
customer_id                       0.00
order_status                      0.00
order_purchase_timestamp          0.00
order_approved_at                 0.01
order_delivered_carrier_date      1.03
order_delivered_customer_date     2.08
order_estimated_delivery_date     0.00
customer_unique_id                0.00
customer_zip_code_prefix          0.00
customer_city                     0.00
customer_state                    0.00
order_item_id                     0.00
product_id                        0.00
seller_id                         0.00
shipping_limit_date               0.00
price                             0.00
freight_value                     0.00
product_category_name             0.00
product_name_lenght               0.00
product_description_lenght        0.00
product_photos_qty                0.00
product_weight_g                  0.00
product_length_cm                 0.00
product_height_cm                 0.00
product_width_cm                  0.00
product_category_name_english     0.00
seller_zip_code_prefix            0.00
seller_city                       0.00
seller_state                      0.00
payment_sequential                0.00
payment_type                      0.00
payment_installments              0.00
payment_value                     0.00
review_id                         0.00
review_score                      0.00
review_comment_title             88.06
review_comment_message           57.70
review_creation_date              0.00
review_answer_timestamp           0.00
delivery_days                     2.08
delivery_delay                    2.08
dtype: float64
----------------------------------------
Quantidade de linhas duplicadas: 0
----------------------------------------
Removendo duplicatas...
----------------------------------------
Verificando se ainda há duplicatas: 0
----------------------------------------
Tratando colunas com valores nulos...
----------------------------------------
Verificando se ainda há colunas com valores nulos igual ou acima de 70%:
order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.000121
order_delivered_carrier_date     0.010337
order_delivered_customer_date    0.020760
order_estimated_delivery_date    0.000000
customer_unique_id               0.000000
customer_zip_code_prefix         0.000000
customer_city                    0.000000
customer_state                   0.000000
order_item_id                    0.000000
product_id                       0.000000
seller_id                        0.000000
shipping_limit_date              0.000000
price                            0.000000
freight_value                    0.000000
product_category_name            0.000000
product_name_lenght              0.000000
product_description_lenght       0.000000
product_photos_qty               0.000000
product_weight_g                 0.000009
product_length_cm                0.000009
product_height_cm                0.000009
product_width_cm                 0.000009
product_category_name_english    0.000000
seller_zip_code_prefix           0.000000
seller_city                      0.000000
seller_state                     0.000000
payment_sequential               0.000000
payment_type                     0.000000
payment_installments             0.000000
payment_value                    0.000000
review_id                        0.000000
review_score                     0.000000
review_comment_message           0.576971
review_creation_date             0.000000
review_answer_timestamp          0.000000
delivery_days                    0.020760
delivery_delay                   0.020760
dtype: float64
----------------------------------------
Como os dados estão no momento:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp,delivery_days,delivery_delay
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,credit_card,1,18.12,a54f0611adc9ed256b57ede6b6eb5114,4,"Não testei o produto ainda, mas ele veio correto e em boas condições. Apenas a caixa que veio bem amassada e danificada, o que ficará chato, pois se trata de um presente.",2017-10-11,2017-10-12 03:43:48,8.0,-8.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,voucher,1,2.00,a54f0611adc9ed256b57ede6b6eb5114,4,"Não testei o produto ainda, mas ele veio correto e em boas condições. Apenas a caixa que veio bem amassada e danificada, o que ficará chato, pois se trata de um presente.",2017-10-11,2017-10-12 03:43:48,8.0,-8.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,voucher,1,18.59,a54f0611adc9ed256b57ede6b6eb5114,4,"Não testei o produto ainda, mas ele veio correto e em boas condições. Apenas a caixa que veio bem amassada e danificada, o que ficará chato, pois se trata de um presente.",2017-10-11,2017-10-12 03:43:48,8.0,-8.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,boleto,1,141.46,8d5266042046a06655c8db133d120ba5,4,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,13.0,-6.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,credit_card,3,179.12,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,2018-08-18,2018-08-22 19:07:58,9.0,-18.0
5,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,credit_card,1,72.20,359d03e676b3c069f62cadba8dd3f6e8,5,O produto foi exatamente o que eu esperava e estava descrito no site e chegou bem antes da data prevista.,2017-12-03,2017-12-05 19:21:58,13.0,-13.0
6,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,credit_card,1,28.62,e50934924e227544ba8246aeb3770dd4,5,NaN,2018-02-17,2018-02-18 13:02:51,2.0,-10.0
7,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,80bb27c7c16e8f973207a5086ab329e2,86320,...,credit_card,6,175.26,89b738e70a1ce346db29a20fb2910161,4,NaN,2017-07-27,2017-07-27 22:48:30,16.0,-6.0
8,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,932afa1e708222e5821dac9cd5db4cae,26525,...,credit_card,3,75.16,07d67dd06ed5f88bef11ef6b464e79ae,5,NaN,2017-05-27,2017-05-28 02:59:57,9.0,-12.0
9,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06,39382392765b6dc74812866ee5ee92a7,99655,...,boleto,1,35.95,fc4af8aea8ec3f1a3cd181d3d0cadbd5,1,NaN,2017-02-03,2017-02-05 01:58:35,9.0,-32.0
10,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,299905e3934e9e181bfb2e164dd4b4f8,18075,...,voucher,1,161.42,abc5655186d40772bd6e410420e6a3ed,5,NaN,2017-08-17,2017-08-18 01:47:32,18.0,-7.0
11,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,299905e3934e9e181bfb2e164dd4b4f8,18075,...,credit_card,1,8.34,abc5655186d40772bd6e410420e6a3ed,5,NaN,2017-08-17,2017-08-18 01:47:32,18.0,-7.0
12,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,f2a85dec752b8517b5e58a06ff3cd937,20780,...,credit_card,1,259.06,15898b543726a832d4137fbef5d1d00e,1,Aguardando retorno da loja,2017-05-30,2017-05-30 23:13:47,12.0,-9.0
13,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,f2a85dec752b8517b5e58a06ff3cd937,20780,...,credit_card,1,259.06,15898b543726a832d4137fbef5d1d00e,1,Aguardando retorno da loja,2017-05-30,2017-05-30 23:13:47,12.0,-9.0
14,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08,782987b81c92239d922aa49d6bd4200b,4278,...,credit_card,1,114.13,a932e1fddc0c17fc26de56687b48f922,4,NaN,2017-07-20,2017-07-22 20:11:54,5.0,-20.0
15,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18,e97109680b052ee858d93a539597bba7,35400,...,boleto,1,50.13,ed220e853e96b629118a3576e02900b6,5,NaN,2018-06-20,2018-06-20 15:31:29,12.0,-29.0
16,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08,e2dfa3127fedbbca9707b36304996dab,4812,...,credit_card,3,32.70,346e42116863ea64d51cef464d8f0c9c,5,NaN,2018-07-31,2018-08-02 21:15:12,4.0,-9.0
17,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21,04cf8185c71090d28baa4407b2e6d600,5271,...,credit_card,1,54.36,8f39f09c22b1ceb6e3eb178d8e50bb8a,4,Gostei do produto,2018-03-13,2018-03-14 10:36:16,11.0,-9.0
18,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04,ccafc1c3f270410521c3c6f3b249870f,74820,...,credit_card,10,146.45,5a8608437f4b52bec5cd143f37258b5e,5,Obrigado pela atenção. Lojas lannister perfeito em tudo.,2018-07-03,2018-07-03 15:10:07,13.0,-13.0
19,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29,6087cfc70fd833cf2db637a5e6e9d76b,88780,...,credit_card,4,43.09,0c00083494717bc36977eb15ba4bba01,5,NaN,2018-01-09,2018-01-12 01:09:35,12.0,-21.0
20,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11,d0ff1a7468fcc46b8fc658ab35d2a12c,13186,...,credit_card,1,29.75,70c498f6918af37d6444d7846449ea5b,5,NaN,2017-11-28,2017-11-28 22:12:02,6.0,-14.0
21,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23,634f09f6075fe9032e6c19609ffe995a,44024,...,voucher,1,62.15,219cf59cf889bc85babbd1cd1fe30f2d,4,NaN,2017-11-09,2017-11-10 01:06:29,13.0,-15.0
22,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23,634f09f6075fe9032e6c19609ffe995a,44024,...,voucher,1,24.86,219cf59cf889bc85babbd1cd1fe30f2d,4,NaN,2017-11-09,2017-11-10 01:06:29,13.0,-15.0
23,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23,634f09f6075fe9032e6c19609ffe995a,44024,...,credit_card,1,5.96,219cf59cf889bc85babbd1cd1fe30f2d,4,NaN,2017-11-09,2017-11-10 01:06:29,13.0,-15.0
24,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28,d699688533772c15a061e8ce81cb56df,4001,...,boleto,1,118.86,38cae21b1b57a95959440380d5b2ef7a,2,"os correios estäo em greve... näo recebi nenhum aviso de atraso, mas de qqer forma a empresa responsável deveria dar alguma resposta sobre o atraso.",2017-10-01,2017-10-01 17:55:21,21.0,11.0
25,f848643eec1d69395095eb3840d2051e,4fa1cd166fa598be6de80fa84eaade43,delivered,2018-03-15 08:52:40,2018-03-15 09:09:31,2018-03-15 19:52:48,2018-03-19 18:08:32,2018-03-29,68954feaafe4dd638f3bd3e2afa174ec,8473,...,credit_card,4,88.90,f3d78d82a38fc81f086b0d810edcf3aa,5,NaN,2018-03-20,2018-03-20 14:35:09,4.0,-10.0
26,2807d0e504d6d4894d41672727bc139f,72ae281627a6102d9b3718528b420f8a,delivered,2018-02-03 20:37:35,2018-02-03 20:50:22,2018-02-05 22:37:28,2018-02-08 16:13:46,2018-02-21,b8df986511d928829c3192c2ed081eba,3323,...,credit_card,1,17.28,e905f4e4e372b175115c1d6c878b5020,3,NaN,2018-02-09,2018-02-11 21:45:20,4.0,-13.0
27,95266dbfb7e20354baba07964dac78d5,a166da34890074091a942054b36e4265,delivered,2018-01-08 07:55:29,2018-01-08 08:07:31,2018-01-24 23:16:37,2018-01-26 17:32:38,2018-02-21,451e48381edab7f1f6dbfa6d728616ff,89070,...,credit_card,3,187.57,1d507207ffd8c75b785304b33e2f6c59,4,NaN,2018-01-27,2018-01-28 11:42:31,18.0,-26.0
28,f3e7c359154d965827355f39d6b1fdac,62b423aab58096ca514ba6aa06be2f98,delivered,2018-08-09 11:44:40,2018-08-10 03:24:51,2018-08-10 12:29:00,2018-08-13 18:24:27,2018-08-17,9c9242ad7f1b52d926ea76778e1c0c57,18052,...,boleto,1,104.11,9a55cbc65c8fad47581da5ebbb2b373e,5,Sempre vou comprar aqui pois é a melhor parabéns,2018-08-14,2018-08-14 21:52:46,4.0,-4.0
29,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12,a25d5f94840d3c6a1a49f271ed83f4ec,21715,...,boleto,1,125.43,6a1a8e54de03ab98e6e8ff56e56e507f,2,Demora muito entregar. Já passou o prazo e ainda não recebi minha encomenda.,2018-03-16,2018-03-20 23:10:58,28.0,9.0

----------------------------------------
Selecionando variáveis pro treinamento...
----------------------------------------
Quantidade de linhas duplicadas após a seleção: 15112
----------------------------------------
Removendo duplicatas...
----------------------------------------
Shape final: (39638, 5)

## Processamento de Linguagem Natural + Modelo de Regressão Logística

In [5]:
# 1. Pré-processamento Linguagem Natural
def pre_processamento_texto(variavel):

    frases = list(variavel)
    
    textos_processados = []
    manter = {'não', 'nem', 'sem', 'mas', 'muito', 'mais', 'só', 'já', 'até', 'depois', 'também'}
    stop_words = set(nltk.corpus.stopwords.words('portuguese')) - manter
    
    for f in frases:
        palavras = re.sub(r'[^\w\s]', '', str(f).lower()) # limpa o texto, deixando somente letras, números e espaços, tudo em minúsculas.
        palavras = nltk.word_tokenize(palavras) # quebra o texto em tokens
        palavras_filtradas = [palavra for palavra in palavras if palavra not in stop_words]  
        palavras_filtradas = ' '.join(palavras_filtradas)
        textos_processados.append(palavras_filtradas)
        
    return pd.Series(textos_processados, index=variavel.index)
    
corpus = list(pre_processamento_texto(dados_limpos['review_comment_message'])) # Documento com os textos

# 2. Definindo rótulos
def rotular(var_score):
    if var_score >= 4:
        return 'Satisfeito'
    if var_score == 3:
        return 'Neutro'
    return 'Insatisfeito'

In [6]:
# 3. Definindo Processo dos dados
# x -> entrada -> matriz com os comentários vetorizados
# y -> saída -> rótulo de satisfação (satisfeito, neutro, insatisfeito)

x = corpus
y = dados_limpos['review_score'].apply(rotular)
print(len(corpus) == len(y))

# Divide os dados em treino e teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, shuffle=True, random_state=42)

# Etapas Pipeline
modelo = Pipeline([
    ('vetorizacao_1', CountVectorizer()), # Criação do modelo BoW (saco de palavras para vetorização)
    ('regressao_logistica', LogisticRegression(max_iter=1000, class_weight='balanced')) # Cria o modelo de regressão logística
])

modelo.fit(x_train,y_train) # Treinando
teste = modelo.predict(x_test) # Testando
teste

True

array(['Neutro', 'Neutro', 'Satisfeito', ..., 'Insatisfeito', 'Neutro',
       'Satisfeito'], dtype=object)

In [7]:
# 4. Validando o modelo -> holdout
print(classification_report(y_test, teste))
print(confusion_matrix(y_test, teste, labels=["Satisfeito", "Neutro", "Insatisfeito"]))

primeiro_resultado = pd.DataFrame({
    'comentario': x_test,
    'sentimento_real': y_test,
    'sentimento_previsto': teste
})
display(primeiro_resultado.head(30))
print((y_test == teste).value_counts())

              precision    recall  f1-score   support

Insatisfeito       0.78      0.78      0.78      2036
      Neutro       0.24      0.36      0.29       692
  Satisfeito       0.93      0.87      0.90      5200

    accuracy                           0.80      7928
   macro avg       0.65      0.67      0.66      7928
weighted avg       0.83      0.80      0.82      7928

[[4533  454  213]
 [ 208  249  235]
 [ 126  331 1579]]

,comentario,sentimento_real,sentimento_previsto
75882,ter mais cuiado hora embala transporte película chegou quebrada não gostei tudo bem comprar outra kit presente mim devolver não compensava,Satisfeito,Neutro
10425,nao recebi produto acredito problema correios prazo entrega expirou,Insatisfeito,Neutro
48346,ok recebido conforme informado,Satisfeito,Satisfeito
22064,ótimo produto linda chaleiracor muito linda,Satisfeito,Satisfeito
85902,recomendo,Satisfeito,Satisfeito
44844,comprei prancha profissional anti frizz 230 bivolte chegou cp9 profissional nao dizendo antifriz não gostei alisamento,Insatisfeito,Insatisfeito
93215,não recebi produto nem avisada falta item lojaquando entrei contatoquase 1 mês depoisé fiquei sabendo produto não entregue pois não havia mais estoque,Insatisfeito,Insatisfeito
33856,adorei,Satisfeito,Satisfeito
42507,tudo ok,Satisfeito,Satisfeito
12429,chegou prazo sem nenhuma discrepância,Satisfeito,Satisfeito
7405,descarrega rápido deixando desligado,Satisfeito,Satisfeito
77853,oleo coco não entregue toalhas entregues,Satisfeito,Insatisfeito
89168,além ótimo produto prazo insuperável entrega 4 dias,Satisfeito,Satisfeito
49467,chegou certinho pode confiar,Satisfeito,Satisfeito
23802,lindooo,Satisfeito,Satisfeito
78200,produto chegou antes prazo,Satisfeito,Satisfeito
65152,produto entregue mais rápido doq esperado,Satisfeito,Satisfeito
100079,recebi produto parceiro dentro prazo prometido perfeitas condiçőes recomendoo voltaria indicar comprar,Satisfeito,Satisfeito
1238,pedi duas cadeiras entregue apenas,Insatisfeito,Insatisfeito
32975,atingiu todas expectativasparabéns,Satisfeito,Satisfeito
36733,ameiproduto lindo otima qualidade,Satisfeito,Satisfeito
78249,recomendo rápida entrega,Satisfeito,Satisfeito
61982,melhores lojas encontrei internet,Satisfeito,Satisfeito
48086,sacolas menores aparentam,Satisfeito,Neutro
8479,gostei chegou dentro prazo,Satisfeito,Satisfeito
90854,ta demorando entrega nao resebi compra ainda,Insatisfeito,Insatisfeito
18418,recomendo,Satisfeito,Satisfeito
14391,produto veio errado até agora não nenhuma resposta loja,Insatisfeito,Insatisfeito
89009,faltando receber produto pulseira masculina couro caveira couro legítimo pedra preto 20,Insatisfeito,Insatisfeito
32499,ainda não recebi chegou ultimamente correios atrasando muito,Neutro,Insatisfeito

review_score
True     6361
False    1567
Name: count, dtype: int64

**Métricas de desempenho do modelo -> Validação holdout**

- Acurácia: o modelo acertou 80% de todas as previsões realizadas.
- Precisão: das previsões feitas para cada classe, a proporção que estava correta.
  - Satisfeito: 93%
  - Neutro: 24%
  - Insatisfeito: 78%
- Recall: dos casos que realmente pertencem a cada classe, a proporção que o modelo conseguiu identificar.
  - Satisfeito: 87%
  - Neutro: 36%
  - Insatisfeito: 78%

- Dos 5200 registros de teste que pertencem à classe 'Satisfeito': 4533 foram identificados pelo modelo como 'Satisfeito', 454 'Neutro' e 213 'Insatisfeito'.
- Dos 692 registros de teste que pertencem à classe 'Neutro': 249 foram identificados pelo modelo como 'Neutro', 208 'Satisfeito' e 235 'Insatisfeito'.
- Dos 2036 registros de teste que pertencem à classe 'Insatisfeito': 1579 foram identificados pelo modelo como 'Insatisfeito', 331 'Neutro' e 126 'Satisfeito'.

In [8]:
# 5. Validando o modelo -> validação cruzada

skfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42) # Objeto de divisão dos dados
y_previsto = cross_val_predict(modelo, x, y, cv=skfold)
print(classification_report(y, y_previsto))
print(confusion_matrix(y, y_previsto, labels=["Satisfeito", "Neutro", "Insatisfeito"]))

segundo_resultado = pd.DataFrame({
    'comentario': x,
    'sentimento_real': y,
    'sentimento_previsto': y_previsto
})
display(segundo_resultado.head(30))
print((y == y_previsto).value_counts())

              precision    recall  f1-score   support

Insatisfeito       0.77      0.77      0.77     10178
      Neutro       0.24      0.35      0.29      3463
  Satisfeito       0.93      0.87      0.90     25997

    accuracy                           0.80     39638
   macro avg       0.65      0.67      0.65     39638
weighted avg       0.83      0.80      0.82     39638

[[22725  2159  1113]
 [ 1026  1226  1211]
 [  603  1698  7877]]

,comentario,sentimento_real,sentimento_previsto
0,não testei produto ainda mas veio correto boas condições apenas caixa veio bem amassada danificada ficará chato pois trata presente,Satisfeito,Satisfeito
3,muito bom produto,Satisfeito,Satisfeito
5,produto exatamente esperava descrito site chegou bem antes data prevista,Satisfeito,Satisfeito
12,aguardando retorno loja,Insatisfeito,Insatisfeito
17,gostei produto,Satisfeito,Satisfeito
18,obrigado atenção lojas lannister perfeito tudo,Satisfeito,Satisfeito
24,correios estäo greve näo recebi nenhum aviso atraso mas qqer forma empresa responsável deveria dar alguma resposta sobre atraso,Insatisfeito,Insatisfeito
28,sempre vou comprar aqui pois melhor parabéns,Satisfeito,Satisfeito
29,demora muito entregar já passou prazo ainda não recebi encomenda,Insatisfeito,Insatisfeito
30,até momento não recebi produto protetor colchão berço algodão impermeável já fiz reclamação desde dia 1806 ainda não obtive retorno irei cancelar pedido estornar compra hj,Insatisfeito,Insatisfeito
32,lindos acabamento incrivel muiro macios super conta,Satisfeito,Satisfeito
35,produto veio faltando base auto fiz pedido telefone justamente confirmar base demonstrada foto acompanhava produto tbm constava descrição item,Insatisfeito,Insatisfeito
36,entregue produto divergente havia comprado além não vir todos acessórios constantes descrição anuncio solicito providências urgentes,Insatisfeito,Insatisfeito
38,ficou tudo ok só pensei q maior masta bom,Satisfeito,Neutro
40,muito tempo efetuo compras atraves desta loja nunca problemas sempre entrega antes data,Satisfeito,Satisfeito
41,bom pode comprar,Satisfeito,Satisfeito
43,produto veio bem lacrado todo original,Satisfeito,Satisfeito
45,quero cartão crédito lojas lannister satisfação plena,Satisfeito,Satisfeito
46,inicialmente data compra produto entregue até 2112 hoje dia 2712 não chegou ainda,Insatisfeito,Insatisfeito
50,cuba veio quebrada efetuo barroca,Insatisfeito,Insatisfeito
53,prazo entrega excelente produto cuidadosamente embalado recomendo,Satisfeito,Satisfeito
57,recebi apenas 1 unidade solicitada deveriam 2 inclusive cobrado consta nota fiscal tentando contato loja 4 dias informam vão mandar email contato fornece,Insatisfeito,Insatisfeito
59,inicialmente pedi cancelamento pedido devido falta atualização produto hoje sei erro aplicativo não vendedor,Satisfeito,Neutro
60,potente grande,Satisfeito,Satisfeito
61,entrega antes data marcada excelente,Satisfeito,Satisfeito
63,pedir 2 capinhasestou pagando duas só veio umaentao não nada satisfeita espero reparado erro,Insatisfeito,Insatisfeito
65,não recebi,Insatisfeito,Insatisfeito
71,somente mala pequena bordo avião 360º viagem seanite preta 12771 entregue auto transformador automático bivolt 5000va até 12000 btus ainda não entregue,Satisfeito,Neutro
73,pensei cinta mais larga muito estreita cargas pesadas,Neutro,Satisfeito
75,agora testar avaliar qualidade mas até agora tudo certo,Satisfeito,Satisfeito

review_score
True     31828
False     7810
Name: count, dtype: int64

**Métricas de desempenho do modelo -> Validação cruzada**

- Acurácia: o modelo acertou 80% de todas as previsões realizadas.
- Precisão: das previsões feitas para cada classe, a proporção que estava correta.
  - Satisfeito: 93%
  - Neutro: 24%
  - Insatisfeito: 77%
- Recall: dos casos que realmente pertencem a cada classe, a proporção que o modelo conseguiu identificar.
  - Satisfeito: 87%
  - Neutro: 35%
  - Insatisfeito: 77%


- Dos 25997 registros da base que pertencem à classe 'Satisfeito': 22725 foram identificados pelo modelo como 'Satisfeito', 2159 'Neutro' e 1113 'Insatisfeito'.
- Dos 3463 registros da base que pertencem à classe 'Neutro': 1226 foram identificados pelo modelo como 'Neutro', 1026 'Satisfeito' e 1211 'Insatisfeito'.
- Dos 10178 registros da base que pertencem à classe 'Insatisfeito': 7877 foram identificados pelo modelo como 'Insatisfeito', 1698 'Neutro' e 603 'Satisfeito'.

**Embora os resultados dos dois métodos de validação sejam bastante próximos, em ambos o modelo tem dificuldade em identificar clientes da classe Neutro (F1 de 0,29). Essa classe representa apenas cerca de 8,7% dos registros, o que dificulta o aprendizado do modelo, e além disso é naturalmente ambígua, pois os erros se distribuem entre Satisfeito e Insatisfeito.**

## Análises descritivas

In [9]:
# Comentários mais ditos -> Visão Macro
c = pd.Series(corpus)
frases_mais_ditas = c.value_counts()
frases_mais_ditas

muito bom                                                                                                                        595
bom                                                                                                                              361
recomendo                                                                                                                        325
otimo                                                                                                                            241
ótimo                                                                                                                            223
                                                                                                                                ...
relógio recebido não condiz foto anúncio creio relógio falso entrei contato loja mas até agora não obtive retorno                  1
comprei relógio veio modelo diferente solicitei                                                                                    1
aguardando resposta até hoje sobre produtos já pagos ainda não recebi 03 iguais necessito falar pessoas não máquina gravações      1
melhor preço entrega super rápida fregues muito tempo loja totalmente confiável                                                    1
parabéns produto chegou esperado entrega super rápida                                                                              1
Name: count, Length: 32046, dtype: int64

In [10]:
# Palavras mais ditas -> Visão Macro
palavras = []
for texto in corpus:
    palavra = texto.split()
    for p in palavra:
        palavras.append(p)
palavras

p = pd.Series(palavras)
palavras_mais_ditas = p.value_counts()
palavras_mais_ditas

produto         17437
não             10022
prazo            8048
muito            7659
entrega          6220
                ...
engual              1
jjjjjj              1
prazopoderia        1
defeitoem           1
enxofre             1
Name: count, Length: 18583, dtype: int64

In [11]:
# Maiores Scores -> Visão Macro
display(dados_limpos['review_score'].value_counts()) # Valor total
display(dados_limpos['review_score'].value_counts()/len(dados_limpos) * 100) # Proporção

review_score
5    20149
1     8118
4     5848
3     3463
2     2060
Name: count, dtype: int64

review_score
5    50.832534
1    20.480347
4    14.753519
3     8.736566
2     5.197033
Name: count, dtype: float64

In [12]:
# Categorias mais Avaliadas -> Visão Macro
display(dados_limpos['product_category_name'].value_counts()/len(dados_limpos)*100)

categoria_mesa_banho = dados_limpos[dados_limpos['product_category_name']== 'cama_mesa_banho']
display(categoria_mesa_banho['review_score'].value_counts()/len(categoria_mesa_banho) * 100) # Para cada nota de avaliação
display(categoria_mesa_banho)

# A categoria cama_mesa_banho é a que apresenta a maior quantidade de registros, 
# aproximadamente 10,6% do dataset. E dentro dessa categoria, há uma predominância de avaliações positivas (cerca de 62%), 
# mas há um valor consideravelmente alto para as notas baixas (cerca de 27%).

product_category_name
cama_mesa_banho                  10.626167
beleza_saude                      8.375801
esporte_lazer                     7.386851
informatica_acessorios            6.806600
moveis_decoracao                  6.352490
                                   ...
fashion_esporte                   0.012614
cds_dvds_musicais                 0.012614
la_cuisine                        0.010091
seguros_e_servicos                0.005046
fashion_roupa_infanto_juvenil     0.002523
Name: count, Length: 71, dtype: float64

review_score
5    48.171890
1    20.892688
4    14.316239
3    10.375119
2     6.244065
Name: count, dtype: float64

,order_id,product_id,product_category_name,review_score,review_comment_message
135,8fc207e94fa91a7649c5a5dab690272a,f2e53dd1670f3c376518263b3f71424d,cama_mesa_banho,3,O prazo de entrega é muito longo
142,f2fa3795760c35b8c05fa8e2f09d5143,120fa011365fc39efe382cba4e50999e,cama_mesa_banho,3,Só foi entregue 1 dos 3 produtos q comprei
146,e37797aedc7cd4ef82278fbc169eecaf,013ee64977aaa6b2b25475095162e0e9,cama_mesa_banho,5,Muito bom entregou até antes do dia 😆😆😆😆😆😆😆😆
150,5164933efe0cd14f31424b9badf81f19,821a07e1e2a0382df1f3761ae3cd435c,cama_mesa_banho,1,Produto não corresponde às expectativas
187,1d067305b599c1e0dceb3864056ea527,2a2d22ae30e026f1893083c8405ca522,cama_mesa_banho,5,muito bom otimo
...,...,...,...,...,...
115532,2b9319f90cac6853394132c982ff27bf,2a2d22ae30e026f1893083c8405ca522,cama_mesa_banho,5,"Muito bom, muito confortável para dormir."
115538,a6bd1f93b7ff72cc348ca07f38ec4bee,c045b19fdb30a3035c56d04c6fe2e622,cama_mesa_banho,5,Foi tudo dentro do esperado!!!
115563,a3480694574e74545579bf7d974318d0,1a428b685ede76217c9efb550c4aaa59,cama_mesa_banho,5,"Gostei muito,super recomendo,recebi antes mesmo do prazo ."
115565,41d74f5b8f1fb05bdec674cbba8f720f,6fdbc2d597f906254d258d8d64d71925,cama_mesa_banho,1,Não gostei imaginei que era uma cortina de tecido bonita . E no entanto é nylon e muito mal acabada e frágil.
115584,6f46d42016226f77893ed3978d6903d0,9cbe4a1fd4db99c14512e9b2ff033ec4,cama_mesa_banho,5,tudo bom e ótimo

In [13]:
# O que fez 20,5% dos pedidos receberem nota 1(insatisfação)?
pior_avaliacao = dados_limpos[dados_limpos['review_score']==1]
pior_avaliacao

,order_id,product_id,product_category_name,review_score,review_comment_message
12,e6ce16cb79ec1d90b1da9085a6118aeb,08574b074924071f4e201e151b152b4e,ferramentas_jardim,1,Aguardando retorno da loja
30,acce194856392f074dbf9dada14d8d82,d70f38e7f79c630f8ea00c993897042c,bebes,1,"Até o momento não recebi o produto Protetor De Colchão Para Berço - Algodão Impermeável, já fiz a reclamação desde o dia 18/06 e ainda não obtive retorno. Irei cancelar o pedido e estornar a compra hj"
36,1790eea0b567cf50911c057cf20f90f9,2d8f2be4f08788ee3bf5356af2b2ee6c,climatizacao,1,"Foi entregue um produto divergente do que eu havia comprado, além de não vir com todos os acessórios constantes na descrição do anuncio. Solicito providências urgentes."
46,6ea2f835b4556291ffdc53fa0b3b95e8,be021417a6acb56b9b50d3fd2714baa8,utilidades_domesticas,1,"Inicialmente, na data da compra o produto era para ser entregue até 21/12. Hoje é dia 27/12 e não chegou ainda."
50,6ebaec694d7025e2ad4a05dba887c032,e251ebd2858be1aa7d9b2087a6992580,ferramentas_jardim,1,A cuba veio quebrada. Como efetuo barroca?
...,...,...,...,...,...
115560,0fa1fab1d7c1211c824596ed5e111e3c,149de4383ccb1829ea75380fc5f0b5fa,beleza_saude,1,"Nao volto a comprar com esta loja , demorando uma vida a enttega deste produto"
115565,41d74f5b8f1fb05bdec674cbba8f720f,6fdbc2d597f906254d258d8d64d71925,cama_mesa_banho,1,Não gostei imaginei que era uma cortina de tecido bonita . E no entanto é nylon e muito mal acabada e frágil.
115586,38e9133ce29f6bbe35aed9c3863dce01,014a8a503291921f7b004a5215bb3c36,bebes,1,nao recebi o produto que ja paguei ! nao recomendo a compra nesse site.
115588,d692ef54145c9cb3322ec2e5508aa3f4,58efb9b638561ce132216a9a612513e2,moveis_sala,1,"Prateleiras com cantos vivo, colunas nao encaixam, faltam arroelas para nao danificar a pintura, prateleiras chegaram todas amassadas."
115595,cfa78b997e329a5295b4ee6972c02979,3d2c44374ee42b3003a470f3e937a2ea,instrumentos_musicais,1,"Ele não é um mini cajon, é um shaker, ou seja, um chocalho que imita o cajon. Péssimo."

In [14]:
display(pior_avaliacao['product_id'].value_counts()/len(pior_avaliacao) * 100) # Proporção produtos com nota 1 -> Visão micro
print(40*'-')
display(pior_avaliacao['product_category_name'].value_counts()/len(pior_avaliacao) * 100) # Proporção categorias com nota 1 -> Visão micro
print(40*'-')

# Percebe-se que qualidade do produto e prazo de entrega são temas recorrentes que podem justificar o recebimento da menor nota: 1 -> Insatisfeito -> visão micro
avaliacao = pior_avaliacao['review_comment_message']
avaliacao = pd.DataFrame(avaliacao)
avaliacao.head(30)

product_id
99a4788cb24856965c36a24e339b6058    0.468096
53759a2ecddad2bb87a079a1f1519f73    0.443459
89b121bee266dcd25688a1ba72eefb61    0.381867
7c1bd920dbdf22470b68bde975dd3ccf    0.344913
422879e10f46682990de24d770e7f83d    0.332594
                                      ...
7e9b52ab8c9b4c0fa93e431e8c3975e4    0.012318
2610a3a6c0250a7f4411801a8cf376c7    0.012318
05f97ad4ce078ed1de8882e1824eb07f    0.012318
7e646f7e1e428a1ddde5a18dd9d42e95    0.012318
74f6a88474993377506706e383f98302    0.012318
Name: count, Length: 5472, dtype: float64

----------------------------------------

product_category_name
cama_mesa_banho           10.840108
informatica_acessorios     8.167036
beleza_saude               8.117763
esporte_lazer              7.538803
moveis_decoracao           7.156935
                            ...
musica                     0.024637
casa_conforto_2            0.024637
la_cuisine                 0.012318
seguros_e_servicos         0.012318
fashion_esporte            0.012318
Name: count, Length: 69, dtype: float64

----------------------------------------

                                                                                                                                                                                         review_comment_message
12                                                                                                                                                                                   Aguardando retorno da loja
30     Até o momento não recebi o produto Protetor De Colchão Para Berço - Algodão Impermeável, já fiz a reclamação desde o dia 18/06 e ainda não obtive retorno. Irei cancelar o pedido e estornar a compra hj
36                                     Foi entregue um produto divergente do que eu havia comprado, além de não vir com todos os acessórios constantes na descrição do anuncio. Solicito providências urgentes.
46                                                                                              Inicialmente, na data da compra o produto era para ser entregue até 21/12. Hoje é dia 27/12 e não chegou ainda.
50                                                                                                                                                                   A cuba veio quebrada. Como efetuo barroca?
57     Recebi apenas 1 unidade solicitada, deveriam ser 2, inclusive foi cobrado e consta na nota fiscal. Estou tentando contato com a loja a 4 dias. Informam que vão me mandar por email o contato do fornece
63                                                                                   Pedir 2 capinhas,estou pagando as duas e só veio uma.Entao não estou nada satisfeita e espero que seja reparado esse erro.
65                                                                                                                                                                                                   Não recebi
94                                                                                                                                                                         Muito bom o produto e preço cobrado!
111                                                                                                                                          Os outros produtos, a loja ofereceu mas não cumpriu com a entrega.
128                                                                                                                                            Boa noite, não recebi o escorredor de louça, Continuo no aguardo
129                                                                                                                                               Não recebi o produto até a presente data na minha residência.
138                                                                                                                                                                  COMO VOU AVALIAR UM PRODUTO QUE NÃO RECEBI
147                                                                                                                                                              mais ou menos o produto veio faltando uma peca
150                                                                                                                                                                     Produto não corresponde às expectativas
157                                                                                                                 Nao gostei do produto pois veio com detalhes no acabamento e com sinais que ja foram uzados
169                                                                                                                                                                                     Recebi um produto velho
172                         Minha opinião é que se comprei o produto ele tinha que ser entregue e não receber um notificação que seria dado como entregue o produto...então a empresa me devolva meu dinheiro!!
208                                                                                                                                        Faltou a FLANGE da cadeira que e considerada a peça mais importante.
256                        Comprei um lençol queen mas as fronhas não vestem um travesseiro 70 x 50. São muito pequenas e estreitas!!! baratheon que sempre ofereceu produtos de qualidade deixou a desejar !!!
270                 Não interessa se opera Market Place. A compra foi feita no site da lannister e pago para lannister. Se tiver que ajuizar vai ser contra lannister e lá faça o regresso contra o fornecedor.
311                                                              Comprei um KiT de 3 Almofadas Azul Mandala e recebi um outro com almofadas diferentes (inclusive as cores) Nâo sei lidar com INCOMPETÊNCIA!!!!
347                                                                                                                                       Comprei um produto e não entregaram. \r\nPedi o cancelado do produto.
353                                                                                                                                                                                                 Não chegou.
354                                                                                                               targaryen não entregou os produtos completos. No dois itens comprados veio faltando unidades.
391  Preciso alizar a troca do produto que está com defeito e não consigo registrar a solicitação no SITE. No item "TROCAS E DEVOLUÇÕES" sempre informa que está com problema de comunicação.\r\nAguardo retorn
402                                                                                                                              Não recebi o pedido no tempo estimado e não fui informada do porque do atraso.
431                                                                                                                                                                Me entregaram faltando um pote, insatisfação
440                                                                                                                                    produto entregue diferente do que foi comprado,não recomendo o vendedor.
450                                                                                                                                                    N gostei do produto n era oq imaginei nem oq eu eeperava

**Conclusão:**

A análise descritiva mostra predominância de avaliações positivas: as notas 5 representam cerca de 50% dos 39638 registros. Somadas às notas 4, que correspondem ao sentimento Satisfeito, chegam a aproximadamente 65,6% do dataset. Por outro lado, as notas 1 representam cerca de 20,5% dos dados. Considerando também as notas 2, a classe Insatisfeito soma 25,7%.

Entre as avaliações nota 1, a categoria cama, mesa e banho concentra a maior parcela (cerca de 10,8%), proporção semelhante ao seu peso no dataset (cerca de 10,6%), o que indica que ela aparece mais por ser a categoria com mais avaliações. Os comentários abrangem desde problemas de qualidade do produto até relatos de falhas na entrega, como atrasos e pedidos que não chegaram. Esses resultados indicam a importância de avaliar a gestão de qualidade dos produtos e investigar as causas dos atrasos nas entregas, incluindo o desempenho das transportadoras. Também é importante ressaltar que dentro dessa categoria, no geral, há uma maior predominância de avaliações positivas, indicando que tais problemas são a minoria mas que requerem melhorias.

Modelo de classificação de sentimento:

Para o caso de comentários sem rótulo, treinei um modelo de regressão logística que prevê o sentimento a partir do texto, usando balanceamento de classes (class_weight='balanced'). O desempenho geral foi bom, com destaque para Satisfeito e Insatisfeito. A classe Neutro (nota 3) teve desempenho inferior, com queda na precisão e no recall, mesmo após o balanceamento.

## Perguntas à serem respondidas

1. Diante da base de dados utilizada (cite qual foi), qual seria um problema relevante e acionável a ser resolvido utilizando Ciência de Dados? Justifique sua escolha com base em possíveis impactos para os negócios, organizações e pessoas possivelmente interessadas e hipóteses levantadas a partir das variáveis disponíveis.

A base utilizada foi o Merged Olist Brazilian E-Commerce Dataset for EDA, disponível no Kaggle, que reúne dados de pedidos, produtos, entregas e avaliações de clientes de um e-commerce brasileiro.

Um problema relevante e acionável é: quando surgirem clientes cujas avaliações não vierem rotuladas (sem nota de satisfação), como identificar o nível de satisfação deles a partir do comentário que escreveram? Esse foi o problema que explorei no meu projeto.

Resolvê-lo traz impacto direto para o negócio. A empresa passa a monitorar a satisfação em larga escala e a entender como a gestão de recursos, os produtos e as transportadoras influenciam a percepção do cliente sobre o recebimento do pedido. Com as causas identificadas, ela pode agir para melhorar a experiência e reduzir a rotatividade de clientes. Vendedores, transportadoras e os próprios clientes também se beneficiam.

Para resolver o problema, iniciei meus estudos em aprendizado de máquina supervisionado e escolhi a regressão logística. Nela, uma variável de entrada (x), o texto do comentário, e rótulos de treinamento (y), a classificação de satisfação, permitem treinar o algoritmo para prever classes discretas para novos comentários

2. Quais ferramentas, bibliotecas e etapas você usou para explorar os dados, fazer tratamento, e criar visualizações úteis para investigar o problema formulado? Cite ao menos duas funções aprendidas nas últimas aulas (ex.: funções em Python, manipulação com Pandas, ou visualizações com matplotlib/seaborn) que seriam essenciais neste processo.

Utilizei Python em um notebook Jupyter, com as seguintes bibliotecas:

- pandas: tratamento dos dados e análise descritiva.
- re: expressões regulares no pré-processamento do texto.
- nltk: processamento de linguagem natural. Como o computador não interpreta palavras, precisei vetorizar o texto, transformando palavras em números.
- scikit-learn: treinamento e validação do modelo com os dados de teste.

As etapas foram: exploração e tratamento dos dados, pré-processamento do texto, vetorização, divisão em treino e teste, treinamento do modelo e avaliação dos resultados. As principais funções do scikit-learn foram:

- CountVectorizer(): cria o modelo Bag of Words para vetorizar o texto.
- LogisticRegression(max_iter=1000, class_weight='balanced'): cria o modelo de regressão logística, com pesos ajustados para compensar classes desbalanceadas.
- classification_report(): apresenta as métricas de desempenho do modelo.
- confusion_matrix(): mostra os acertos e erros de cada classe.

3. Suponha que, ao aplicar uma análise exploratória, você percebe que uma variável da sua base de dados apresenta assimetria à direita e muitos outliers. Como você interpretaria esse comportamento estatístico e como isso afetaria sua decisão ao propor soluções? Como comunicaria isso para uma equipe não técnica?

Uma assimetria à direita indica que a maior parte dos dados se concentra em valores baixos, enquanto os valores altos são mais raros e dispersos, formando uma cauda longa à direita. Com isso, a média é puxada para cima e fica acima da mediana, deixando de representar bem o valor típico.

Eu confirmaria os outliers por cálculo, usando o IQR e os limites inferior (Q1 − 1,5 × IQR) e superior (Q3 + 1,5 × IQR). Em seguida, seria meu papel como analista investigar a origem deles: podem ser situações raras, mas legítimas, medições incorretas, falhas de entrada ou anomalias. Ignorar essa limitação pode levar a análises imprecisas e a prejuízos financeiros e operacionais.

Isso também afetaria minhas decisões. Eu usaria a mediana em vez da média para descrever o valor típico, decidiria caso a caso entre manter, tratar ou remover os outliers.

Para uma equipe não técnica, eu diria: “Pessoal, a maior parte dos valores dessa variável é baixa, e a média acaba sendo puxada para cima por poucos casos muito altos. Por isso, o valor mais comum é menor do que a média sugere. Esses valores altos podem ser casos reais e raros ou erros de registro, e estou investigando para que as decisões de vocês sejam baseadas em informações mais precisas.”

4. Após finalizar o projeto, como você avalia a relevância dele para seu portfólio como Cientista de Dados? O que destacaria como diferencial técnico e como ponto de melhoria se tivesse que refazer o Projeto Prático III?

Considero este projeto fundamental para o início da minha trajetória em ciência de dados. Todos os projetos anteriores envolviam analisar dados do passado para compreender o presente e apoiar decisões. Neste, pela primeira vez, apliquei aprendizado de máquina para prever classificações em um contexto de e-commerce, usando a biblioteca scikit-learn. Ainda não domino todas as técnicas de machine learning nem todas as funções da biblioteca, mas estou satisfeita com esse começo em processamento de linguagem natural e regressão logística.

Como diferencial técnico, destaco o tratamento do desbalanceamento das classes com class_weight='balanced' e a avaliação do modelo por classification_report e matriz de confusão, e não apenas pela acurácia.

Se refizesse o projeto, aprimoraria o pré-processamento do texto, por exemplo removendo acentos, e testaria outras técnicas, como TF-IDF. Também incluiria visualizações, que não utilizei.